#!/bin/env dls-python

import mypanda as p

seq1 = p.sequencer(1)

# repeats, mask, cond, p1out, p2out, p1time, p2time
seq1.table(10, 1, 15, 0, 63, 1, 1)
seq1.table(10, 2, 15, 0, 63, 1, 1)
seq1.table(10, 4, 15, 0, 63, 1, 1)
seq1.table(10, 8, 15, 0, 63, 1, 1)
seq1.table(10, 9, 8 , 0, 63, 1, 1)
seq1.table(10, 15, 0 , 0, 63, 1, 1)
