#!/bin/sh

cd "$(dirname "$0")"

# Search for files with trailing whitespace and overlength lines
grep --exclude-dir=build --exclude-dir=.git --exclude=description -rIl \
    ' $\|.\{81\}' .

# Search for files missing the newline at end of file
pcregrep --exclude_dir='build|.git' --exclude=.*.pyc -rl -LM '\n$' .
