#!/bin/sh

HERE="$(dirname "$0")"

CONFIG_DB="$HERE"/config/config
REGISTER_DB="$HERE"/config/registers
DESCRIPTION_DB="$HERE"/config/description

CONFIG_PORT=8888
DATA_PORT=8889

"$HERE"/simulation/sim_server.py &

valgrind --leak-check=full --track-origins=yes \
    "$HERE"/build/sim_server/server \
    -p$CONFIG_PORT -d$DATA_PORT -R \
    -c"$CONFIG_DB" -r"$REGISTER_DB" -D"$DESCRIPTION_DB"
