# Filter block textio files removal
remove_files -fileset sim_1 {../hdl_timing/bits/timing001/1bitsexpected.csv
../hdl_timing/calc/timing001/1calcexpected.csv
../hdl_timing/calc/timing002/2calcexpected.csv
../hdl_timing/clocks/timing001/1clocksexpected.csv
../hdl_timing/clocks/timing002/2clocksexpected.csv
../hdl_timing/counter/timing001/1counterexpected.csv
../hdl_timing/counter/timing002/2counterexpected.csv
../hdl_timing/counter/timing003/3counterexpected.csv
../hdl_timing/counter/timing004/4counterexpected.csv
../hdl_timing/counter/timing005/5counterexpected.csv
../hdl_timing/counter/timing006/6counterexpected.csv
../hdl_timing/counter/timing007/7counterexpected.csv
../hdl_timing/div/timing001/1divexpected.csv
../hdl_timing/div/timing002/2divexpected.csv
../hdl_timing/div/timing003/3divexpected.csv
../hdl_timing/filter/timing001/1filterexpected.csv
../hdl_timing/filter/timing002/2filterexpected.csv
../hdl_timing/filter/timing003/3filterexpected.csv
../hdl_timing/filter/timing004/4filterexpected.csv
../hdl_timing/filter/timing005/5filterexpected.csv
../hdl_timing/filter/timing006/6filterexpected.csv
../hdl_timing/filter/timing007/7filterexpected.csv
../hdl_timing/filter/timing008/8filterexpected.csv
../hdl_timing/filter/timing009/9filterexpected.csv
../hdl_timing/lut/timing001/1lutexpected.csv
../hdl_timing/lut/timing002/2lutexpected.csv
../hdl_timing/lut/timing003/3lutexpected.csv
../hdl_timing/lut/timing004/4lutexpected.csv
../hdl_timing/lut/timing005/5lutexpected.csv
../hdl_timing/lut/timing006/6lutexpected.csv
../hdl_timing/lut/timing007/7lutexpected.csv
../hdl_timing/pcomp/timing001/1pcompexpected.csv
../hdl_timing/pcomp/timing002/2pcompexpected.csv
../hdl_timing/pcomp/timing003/3pcompexpected.csv
../hdl_timing/pcomp/timing004/4pcompexpected.csv
../hdl_timing/pcomp/timing005/5pcompexpected.csv
../hdl_timing/pcomp/timing006/6pcompexpected.csv
../hdl_timing/pcomp/timing007/7pcompexpected.csv
../hdl_timing/pcomp/timing008/8pcompexpected.csv
../hdl_timing/pcomp/timing009/9pcompexpected.csv
../hdl_timing/pcomp/timing010/10pcompexpected.csv
../hdl_timing/pcomp/timing011/11pcompexpected.csv
../hdl_timing/pcomp/timing012/12pcompexpected.csv
../hdl_timing/pcomp/timing013/13pcompexpected.csv
../hdl_timing/pcomp/timing014/14pcompexpected.csv
../hdl_timing/pcomp/timing015/15pcompexpected.csv
../hdl_timing/pcomp/timing016/16pcompexpected.csv
../hdl_timing/pcomp/timing017/17pcompexpected.csv
../hdl_timing/pcomp/timing018/18pcompexpected.csv
../hdl_timing/pcomp/timing019/19pcompexpected.csv
../hdl_timing/pcomp/timing020/20pcompexpected.csv
../hdl_timing/pcomp/timing021/21pcompexpected.csv
../hdl_timing/posenc/timing001/1posencexpected.csv
../hdl_timing/pulse/timing001/1pulseexpected.csv
../hdl_timing/pulse/timing002/2pulseexpected.csv
../hdl_timing/pulse/timing003/3pulseexpected.csv
../hdl_timing/pulse/timing004/4pulseexpected.csv
../hdl_timing/pulse/timing005/5pulseexpected.csv
../hdl_timing/pulse/timing006/6pulseexpected.csv
../hdl_timing/pulse/timing007/7pulseexpected.csv
../hdl_timing/pulse/timing008/8pulseexpected.csv
../hdl_timing/qdec/timing001/1qdecexpected.csv
../hdl_timing/qdec/timing002/2qdecexpected.csv
../hdl_timing/qdec/timing003/3qdecexpected.csv
../hdl_timing/qdec/timing004/4qdecexpected.csv
../hdl_timing/qdec/timing005/5qdecexpected.csv
../hdl_timing/srgate/timing001/1srgateexpected.csv
../hdl_timing/srgate/timing002/2srgateexpected.csv
../hdl_timing/srgate/timing003/3srgateexpected.csv
../hdl_timing/srgate/timing004/4srgateexpected.csv
../hdl_timing/srgate/timing005/5srgateexpected.csv
../hdl_timing/srgate/timing006/6srgateexpected.csv
../hdl_timing/srgate/timing007/7srgateexpected.csv
../hdl_timing/srgate/timing008/8srgateexpected.csv
../hdl_timing/srgate/timing009/9srgateexpected.csv
../hdl_timing/srgate/timing010/10srgateexpected.csv
../hdl_timing/srgate/timing011/11srgateexpected.csv
../hdl_timing/srgate/timing012/12srgateexpected.csv
../hdl_timing/srgate/timing013/13srgateexpected.csv
}

set_property SOURCE_SET sources_1 [get_filesets sim_1]
add_files -fileset sim_1 -norecurse {../hdl_timing/bits/timing001/1bitsexpected.csv
../hdl_timing/calc/timing001/1calcexpected.csv
../hdl_timing/calc/timing002/2calcexpected.csv
../hdl_timing/clocks/timing001/1clocksexpected.csv
../hdl_timing/clocks/timing002/2clocksexpected.csv
../hdl_timing/counter/timing001/1counterexpected.csv
../hdl_timing/counter/timing002/2counterexpected.csv
../hdl_timing/counter/timing003/3counterexpected.csv
../hdl_timing/counter/timing004/4counterexpected.csv
../hdl_timing/counter/timing005/5counterexpected.csv
../hdl_timing/counter/timing006/6counterexpected.csv
../hdl_timing/counter/timing007/7counterexpected.csv
../hdl_timing/div/timing001/1divexpected.csv
../hdl_timing/div/timing002/2divexpected.csv
../hdl_timing/div/timing003/3divexpected.csv
../hdl_timing/filter/timing001/1filterexpected.csv
../hdl_timing/filter/timing002/2filterexpected.csv
../hdl_timing/filter/timing003/3filterexpected.csv
../hdl_timing/filter/timing004/4filterexpected.csv
../hdl_timing/filter/timing005/5filterexpected.csv
../hdl_timing/filter/timing006/6filterexpected.csv
../hdl_timing/filter/timing007/7filterexpected.csv
../hdl_timing/filter/timing008/8filterexpected.csv
../hdl_timing/filter/timing009/9filterexpected.csv
../hdl_timing/lut/timing001/1lutexpected.csv
../hdl_timing/lut/timing002/2lutexpected.csv
../hdl_timing/lut/timing003/3lutexpected.csv
../hdl_timing/lut/timing004/4lutexpected.csv
../hdl_timing/lut/timing005/5lutexpected.csv
../hdl_timing/lut/timing006/6lutexpected.csv
../hdl_timing/lut/timing007/7lutexpected.csv
../hdl_timing/pcomp/timing001/1pcompexpected.csv
../hdl_timing/pcomp/timing002/2pcompexpected.csv
../hdl_timing/pcomp/timing003/3pcompexpected.csv
../hdl_timing/pcomp/timing004/4pcompexpected.csv
../hdl_timing/pcomp/timing005/5pcompexpected.csv
../hdl_timing/pcomp/timing006/6pcompexpected.csv
../hdl_timing/pcomp/timing007/7pcompexpected.csv
../hdl_timing/pcomp/timing008/8pcompexpected.csv
../hdl_timing/pcomp/timing009/9pcompexpected.csv
../hdl_timing/pcomp/timing010/10pcompexpected.csv
../hdl_timing/pcomp/timing011/11pcompexpected.csv
../hdl_timing/pcomp/timing012/12pcompexpected.csv
../hdl_timing/pcomp/timing013/13pcompexpected.csv
../hdl_timing/pcomp/timing014/14pcompexpected.csv
../hdl_timing/pcomp/timing015/15pcompexpected.csv
../hdl_timing/pcomp/timing016/16pcompexpected.csv
../hdl_timing/pcomp/timing017/17pcompexpected.csv
../hdl_timing/pcomp/timing018/18pcompexpected.csv
../hdl_timing/pcomp/timing019/19pcompexpected.csv
../hdl_timing/pcomp/timing020/20pcompexpected.csv
../hdl_timing/pcomp/timing021/21pcompexpected.csv
../hdl_timing/posenc/timing001/1posencexpected.csv
../hdl_timing/pulse/timing001/1pulseexpected.csv
../hdl_timing/pulse/timing002/2pulseexpected.csv
../hdl_timing/pulse/timing003/3pulseexpected.csv
../hdl_timing/pulse/timing004/4pulseexpected.csv
../hdl_timing/pulse/timing005/5pulseexpected.csv
../hdl_timing/pulse/timing006/6pulseexpected.csv
../hdl_timing/pulse/timing007/7pulseexpected.csv
../hdl_timing/pulse/timing008/8pulseexpected.csv
../hdl_timing/qdec/timing001/1qdecexpected.csv
../hdl_timing/qdec/timing002/2qdecexpected.csv
../hdl_timing/qdec/timing003/3qdecexpected.csv
../hdl_timing/qdec/timing004/4qdecexpected.csv
../hdl_timing/qdec/timing005/5qdecexpected.csv
../hdl_timing/srgate/timing001/1srgateexpected.csv
../hdl_timing/srgate/timing002/2srgateexpected.csv
../hdl_timing/srgate/timing003/3srgateexpected.csv
../hdl_timing/srgate/timing004/4srgateexpected.csv
../hdl_timing/srgate/timing005/5srgateexpected.csv
../hdl_timing/srgate/timing006/6srgateexpected.csv
../hdl_timing/srgate/timing007/7srgateexpected.csv
../hdl_timing/srgate/timing008/8srgateexpected.csv
../hdl_timing/srgate/timing009/9srgateexpected.csv
../hdl_timing/srgate/timing010/10srgateexpected.csv
../hdl_timing/srgate/timing011/11srgateexpected.csv
../hdl_timing/srgate/timing012/12srgateexpected.csv
../hdl_timing/srgate/timing013/13srgateexpected.csv
../hdl_timing/qdec/timing001/1qdecexpected.csv
}
