create_ip -vlnv [get_ipdefs -filter {NAME == vio}] -module_name picxo_vio -dir $BUILD_DIR/

set_property -dict [list \
  CONFIG.C_NUM_PROBE_IN {0} \
  CONFIG.C_NUM_PROBE_OUT {15} \
  CONFIG.C_PROBE_OUT0_INIT_VAL {0x08} \
  CONFIG.C_PROBE_OUT0_WIDTH {5} \
  CONFIG.C_PROBE_OUT12_WIDTH {7} \
  CONFIG.C_PROBE_OUT13_WIDTH {10} \
  CONFIG.C_PROBE_OUT14_WIDTH {10} \
  CONFIG.C_PROBE_OUT1_INIT_VAL {0x10} \
  CONFIG.C_PROBE_OUT1_WIDTH {5} \
  CONFIG.C_PROBE_OUT2_INIT_VAL {0x0200} \
  CONFIG.C_PROBE_OUT2_WIDTH {16} \
  CONFIG.C_PROBE_OUT3_INIT_VAL {0x0200} \
  CONFIG.C_PROBE_OUT3_WIDTH {16} \
  CONFIG.C_PROBE_OUT4_INIT_VAL {0x4} \
  CONFIG.C_PROBE_OUT4_WIDTH {4} \
  CONFIG.C_PROBE_OUT5_INIT_VAL {0x0003ff} \
  CONFIG.C_PROBE_OUT5_WIDTH {24} \
  CONFIG.C_PROBE_OUT6_WIDTH {22} \
] [get_ips picxo_vio]

