#
# Create SFP sync mgt core for Ultrascale+
create_ip -vlnv [get_ipdefs -filter {NAME == gtwizard_ultrascale}] \
-module_name sfp_panda_sync_us -dir $BUILD_DIR/

set_property -dict [list \
  CONFIG.DISABLE_LOC_XDC {true} \
  CONFIG.CHANNEL_ENABLE {X0Y5} \
  CONFIG.LOCATE_RX_USER_CLOCKING {CORE} \
  CONFIG.LOCATE_TX_USER_CLOCKING {CORE} \
  CONFIG.RX_COMMA_ALIGN_WORD {4} \
  CONFIG.RX_COMMA_M_ENABLE {true} \
  CONFIG.RX_COMMA_PRESET {K28.5} \
  CONFIG.RX_COMMA_P_ENABLE {true} \
  CONFIG.RX_COMMA_SHOW_REALIGN_ENABLE {false} \
  CONFIG.RX_COMMA_VALID_ONLY {0} \
  CONFIG.RX_DATA_DECODING {8B10B} \
  CONFIG.RX_LINE_RATE {5} \
  CONFIG.RX_MASTER_CHANNEL {X0Y5} \
  CONFIG.RX_PLL_TYPE {CPLL} \
  CONFIG.RX_REFCLK_FREQUENCY {125} \
  CONFIG.RX_REFCLK_SOURCE {X0Y5 clk1} \
  CONFIG.TX_DATA_ENCODING {8B10B} \
  CONFIG.TX_LINE_RATE {5} \
  CONFIG.TX_MASTER_CHANNEL {X0Y5} \
  CONFIG.TX_PLL_TYPE {CPLL} \
  CONFIG.TX_REFCLK_FREQUENCY {125} \
  CONFIG.TX_REFCLK_SOURCE {X0Y5 clk1} \
] [get_ips sfp_panda_sync_us]


