webtalk_init -webtalk_dir /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/sim/panda_top/bench/zynq_model/zynq_ps.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Sep 26 16:16:43 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1215546" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174450382_177743539_210595668_222" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e4a84542-b756-49bf-aafa-fc6ca7af2ee1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5c989478-7cef-43cc-a58e-b337085d6280" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseWorkstation" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Workstation release 6.7 (Santiago)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3101.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 1622581915 -regid "174450382_177743539_210595668_222" -xml /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/sim/panda_top/bench/zynq_model/zynq_ps.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/sim/panda_top/bench/zynq_model/zynq_ps.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/sim/panda_top/bench/zynq_model/zynq_ps.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
