#!/bin/sh

set -e

# This script assembles all the components required for a Panda install and
# creates the target package.

TOP="${1:?}"
BUILD_DIR="${2:?}"
ZPKG="${3:?}"

error() { echo >&2 "$@"; exit 1; }

# Pick up the skeleton name from the ZPKG name.
[[ $ZPKG =~ "$BUILD_DIR"/(.*)@.*\.zpg ]]  ||  error Invalid package name
PKG_NAME="${BASH_REMATCH[1]}"
FILE_LIST="$TOP/etc/$PKG_NAME".list
[[ -r "$FILE_LIST" ]]  ||  error Unable to read "$FILE_LIST"

# Create empty skeleton
ZPKG_DIR="$BUILD_DIR"/zpkg-$PKG_NAME

rm -f "$BUILD_DIR"/$PKG_NAME@*.zpg  &&
rm -rf "$ZPKG_DIR"  &&

while read action target source; do
    case $action in
        \#) ;;
        d)  mkdir -p "$ZPKG_DIR"/$target ;;
        t)  cp "$TOP"/$source "$ZPKG_DIR"/$target ;;
        b)  cp "$BUILD_DIR"/$source "$ZPKG_DIR"/$target ;;
        l)  ln -s $source "$ZPKG_DIR"/$target ;;
        *)  error Invalid action ;;
    esac
done <"$FILE_LIST"

# Assemble final package
tar czf $ZPKG -C "$ZPKG_DIR" $(cd "$ZPKG_DIR"; echo *) --owner=0 --group=0
