--------------------------------------------------------------------------------
--  File:       bits_ctrl.vhd
--  Desc:       Autogenerated block control module.
--
--  Author:     Isa Uzun - Diamond Light Source
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.addr_defines.all;
use work.top_defines.all;

entity bits_ctrl is
port (
    -- Clock and Reset
    clk_i               : in std_logic;
    reset_i             : in std_logic;
    sysbus_i            : in sysbus_t;
    posbus_i            : in posbus_t;
    -- Block Parameters
    A       : out std_logic_vector(31 downto 0);
    A_WSTB  : out std_logic;
    B       : out std_logic_vector(31 downto 0);
    B_WSTB  : out std_logic;
    C       : out std_logic_vector(31 downto 0);
    C_WSTB  : out std_logic;
    D       : out std_logic_vector(31 downto 0);
    D_WSTB  : out std_logic;
    -- Memory Bus Interface
    read_strobe_i       : in  std_logic;
    read_address_i      : in  std_logic_vector(BLK_AW-1 downto 0);
    read_data_o         : out std_logic_vector(31 downto 0);
    read_ack_o          : out std_logic;

    write_strobe_i      : in  std_logic;
    write_address_i     : in  std_logic_vector(BLK_AW-1 downto 0);
    write_data_i        : in  std_logic_vector(31 downto 0);
    write_ack_o         : out std_logic
);
end bits_ctrl;

architecture rtl of bits_ctrl is

signal read_addr        : natural range 0 to (2**read_address_i'length - 1);
signal write_addr       : natural range 0 to (2**write_address_i'length - 1);


begin

-- Unused outputs
read_ack_o <= '0';
write_ack_o <= '0';

read_addr <= to_integer(unsigned(read_address_i));
write_addr <= to_integer(unsigned(write_address_i));

--
-- Control System Interface
--
REG_WRITE : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            A <= (others => '0');
            A_WSTB <= '0';
            B <= (others => '0');
            B_WSTB <= '0';
            C <= (others => '0');
            C_WSTB <= '0';
            D <= (others => '0');
            D_WSTB <= '0';
        else
            A_WSTB <= '0';
            B_WSTB <= '0';
            C_WSTB <= '0';
            D_WSTB <= '0';

            if (write_strobe_i = '1') then
                -- Input Select Control Registers
                if (write_addr = BITS_A) then
                    A <= write_data_i;
                    A_WSTB <= '1';
                end if;
                if (write_addr = BITS_B) then
                    B <= write_data_i;
                    B_WSTB <= '1';
                end if;
                if (write_addr = BITS_C) then
                    C <= write_data_i;
                    C_WSTB <= '1';
                end if;
                if (write_addr = BITS_D) then
                    D <= write_data_i;
                    D_WSTB <= '1';
                end if;

            end if;
        end if;
    end if;
end process;

--
-- Status Register Read
--
REG_READ : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            read_data_o <= (others => '0');
        else
            case (read_addr) is
                when others =>
                    read_data_o <= (others => '0');
            end case;
        end if;
    end if;
end process;

--
-- Instantiate Delay Blocks for System and Position Bus Fields
--



end rtl;