--------------------------------------------------------------------------------
--  File:       counter_ctrl.vhd
--  Desc:       Autogenerated block control module.
--
--  Author:     Isa Uzun - Diamond Light Source
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.addr_defines.all;
use work.top_defines.all;

entity counter_ctrl is
port (
    -- Clock and Reset
    clk_i               : in std_logic;
    reset_i             : in std_logic;
    sysbus_i            : in sysbus_t;
    posbus_i            : in posbus_t;
    -- Block Parameters
    DIR       : out std_logic_vector(31 downto 0);
    DIR_WSTB  : out std_logic;
    START       : out std_logic_vector(31 downto 0);
    START_WSTB  : out std_logic;
    STEP       : out std_logic_vector(31 downto 0);
    STEP_WSTB  : out std_logic;
    enable_o : out std_logic;
    trig_o : out std_logic;
    -- Memory Bus Interface
    read_strobe_i       : in  std_logic;
    read_address_i      : in  std_logic_vector(BLK_AW-1 downto 0);
    read_data_o         : out std_logic_vector(31 downto 0);
    read_ack_o          : out std_logic;

    write_strobe_i      : in  std_logic;
    write_address_i     : in  std_logic_vector(BLK_AW-1 downto 0);
    write_data_i        : in  std_logic_vector(31 downto 0);
    write_ack_o         : out std_logic
);
end counter_ctrl;

architecture rtl of counter_ctrl is

signal read_addr        : natural range 0 to (2**read_address_i'length - 1);
signal write_addr       : natural range 0 to (2**write_address_i'length - 1);

signal ENABLE      : std_logic_vector(31 downto 0);
signal ENABLE_WSTB : std_logic;
signal ENABLE_DLY      : std_logic_vector(31 downto 0);
signal ENABLE_DLY_WSTB : std_logic;
signal TRIG      : std_logic_vector(31 downto 0);
signal TRIG_WSTB : std_logic;
signal TRIG_DLY      : std_logic_vector(31 downto 0);
signal TRIG_DLY_WSTB : std_logic;

begin

-- Unused outputs
read_ack_o <= '0';
write_ack_o <= '0';

read_addr <= to_integer(unsigned(read_address_i));
write_addr <= to_integer(unsigned(write_address_i));

--
-- Control System Interface
--
REG_WRITE : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            DIR <= (others => '0');
            DIR_WSTB <= '0';
            START <= (others => '0');
            START_WSTB <= '0';
            STEP <= (others => '0');
            STEP_WSTB <= '0';
            ENABLE <= (others => '0');
            ENABLE_WSTB <= '0';
            ENABLE_DLY <= (others => '0');
            ENABLE_DLY_WSTB <= '0';
            TRIG <= (others => '0');
            TRIG_WSTB <= '0';
            TRIG_DLY <= (others => '0');
            TRIG_DLY_WSTB <= '0';
        else
            DIR_WSTB <= '0';
            START_WSTB <= '0';
            STEP_WSTB <= '0';
            ENABLE_WSTB <= '0';
            ENABLE_DLY_WSTB <= '0';
            TRIG_WSTB <= '0';
            TRIG_DLY_WSTB <= '0';

            if (write_strobe_i = '1') then
                -- Input Select Control Registers
                if (write_addr = COUNTER_DIR) then
                    DIR <= write_data_i;
                    DIR_WSTB <= '1';
                end if;
                if (write_addr = COUNTER_START) then
                    START <= write_data_i;
                    START_WSTB <= '1';
                end if;
                if (write_addr = COUNTER_STEP) then
                    STEP <= write_data_i;
                    STEP_WSTB <= '1';
                end if;
                if (write_addr = COUNTER_ENABLE) then
                    ENABLE <= write_data_i;
                    ENABLE_WSTB <= '1';
                end if;
                if (write_addr = COUNTER_ENABLE_DLY) then
                    ENABLE_DLY <= write_data_i;
                    ENABLE_DLY_WSTB <= '1';
                end if;
                if (write_addr = COUNTER_TRIG) then
                    TRIG <= write_data_i;
                    TRIG_WSTB <= '1';
                end if;
                if (write_addr = COUNTER_TRIG_DLY) then
                    TRIG_DLY <= write_data_i;
                    TRIG_DLY_WSTB <= '1';
                end if;

            end if;
        end if;
    end if;
end process;

--
-- Status Register Read
--
REG_READ : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            read_data_o <= (others => '0');
        else
            case (read_addr) is
                when others =>
                    read_data_o <= (others => '0');
            end case;
        end if;
    end if;
end process;

--
-- Instantiate Delay Blocks for System and Position Bus Fields
--
bitmux_ENABLE : entity work.bitmux
port map (
    clk_i       => clk_i,
    sysbus_i    => sysbus_i,
    bit_o       => enable_o,
    BITMUX_SEL  => ENABLE,
    BIT_DLY     => ENABLE_DLY
);

bitmux_TRIG : entity work.bitmux
port map (
    clk_i       => clk_i,
    sysbus_i    => sysbus_i,
    bit_o       => trig_o,
    BITMUX_SEL  => TRIG,
    BIT_DLY     => TRIG_DLY
);




end rtl;