--------------------------------------------------------------------------------
--  File:       sfp_ctrl.vhd
--  Desc:       Autogenerated block control module.
--
--  Author:     Isa Uzun - Diamond Light Source
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.addr_defines.all;
use work.top_defines.all;

entity sfp_ctrl is
port (
    -- Clock and Reset
    clk_i               : in std_logic;
    reset_i             : in std_logic;
    sysbus_i            : in sysbus_t;
    posbus_i            : in posbus_t;
    -- Block Parameters
    LINK1_UP       : in  std_logic_vector(31 downto 0);
    ERROR1_COUNT       : in  std_logic_vector(31 downto 0);
    LINK2_UP       : in  std_logic_vector(31 downto 0);
    ERROR2_COUNT       : in  std_logic_vector(31 downto 0);
    LINK3_UP       : in  std_logic_vector(31 downto 0);
    ERROR3_COUNT       : in  std_logic_vector(31 downto 0);
    SFP_CLK1       : in  std_logic_vector(31 downto 0);
    SFP_CLK2       : in  std_logic_vector(31 downto 0);
    SFP_CLK3       : in  std_logic_vector(31 downto 0);
    SOFT_RESET       : out std_logic_vector(31 downto 0);
    SOFT_RESET_WSTB  : out std_logic;
    -- Memory Bus Interface
    mem_cs_i            : in  std_logic;
    mem_wstb_i          : in  std_logic;
    mem_addr_i          : in  std_logic_vector(BLK_AW-1 downto 0);
    mem_dat_i           : in  std_logic_vector(31 downto 0);
    mem_dat_o           : out std_logic_vector(31 downto 0)
);
end sfp_ctrl;

architecture rtl of sfp_ctrl is

signal mem_addr : natural range 0 to (2**mem_addr_i'length - 1);


begin

mem_addr <= to_integer(unsigned(mem_addr_i));

--
-- Control System Interface
--
REG_WRITE : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            SOFT_RESET <= (others => '0');
            SOFT_RESET_WSTB <= '0';
        else
            SOFT_RESET_WSTB <= '0';

            if (mem_cs_i = '1' and mem_wstb_i = '1') then
                -- Input Select Control Registers
                if (mem_addr = SFP_SOFT_RESET) then
                    SOFT_RESET <= mem_dat_i;
                    SOFT_RESET_WSTB <= '1';
                end if;

            end if;
        end if;
    end if;
end process;

--
-- Status Register Read
--
REG_READ : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            mem_dat_o <= (others => '0');
        else
            case (mem_addr) is
                when SFP_LINK1_UP =>
                    mem_dat_o <= LINK1_UP;
                when SFP_ERROR1_COUNT =>
                    mem_dat_o <= ERROR1_COUNT;
                when SFP_LINK2_UP =>
                    mem_dat_o <= LINK2_UP;
                when SFP_ERROR2_COUNT =>
                    mem_dat_o <= ERROR2_COUNT;
                when SFP_LINK3_UP =>
                    mem_dat_o <= LINK3_UP;
                when SFP_ERROR3_COUNT =>
                    mem_dat_o <= ERROR3_COUNT;
                when SFP_SFP_CLK1 =>
                    mem_dat_o <= SFP_CLK1;
                when SFP_SFP_CLK2 =>
                    mem_dat_o <= SFP_CLK2;
                when SFP_SFP_CLK3 =>
                    mem_dat_o <= SFP_CLK3;
                when others =>
                    mem_dat_o <= (others => '0');
            end case;
        end if;
    end if;
end process;

--
-- Instantiate Delay Blocks for System and Position Bus Fields
--



end rtl;