--------------------------------------------------------------------------------
--  File:       slow_ctrl.vhd
--  Desc:       Autogenerated block control module.
--
--  Author:     Isa Uzun - Diamond Light Source
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.addr_defines.all;
use work.top_defines.all;

entity slow_ctrl is
port (
    -- Clock and Reset
    clk_i               : in std_logic;
    reset_i             : in std_logic;
    sysbus_i            : in sysbus_t;
    posbus_i            : in posbus_t;
    -- Block Parameters
    TEMP_PSU       : in  std_logic_vector(31 downto 0);
    TEMP_SFP       : in  std_logic_vector(31 downto 0);
    TEMP_ENC_L       : in  std_logic_vector(31 downto 0);
    TEMP_PICO       : in  std_logic_vector(31 downto 0);
    TEMP_ENC_R       : in  std_logic_vector(31 downto 0);
    ALIM_12V0       : in  std_logic_vector(31 downto 0);
    PICO_5V0       : in  std_logic_vector(31 downto 0);
    IO_5V0       : in  std_logic_vector(31 downto 0);
    SFP_3V3       : in  std_logic_vector(31 downto 0);
    FMC_15VN       : in  std_logic_vector(31 downto 0);
    FMC_15VP       : in  std_logic_vector(31 downto 0);
    ENC_24V       : in  std_logic_vector(31 downto 0);
    FMC_12V       : in  std_logic_vector(31 downto 0);
    -- Memory Bus Interface
    read_strobe_i       : in  std_logic;
    read_address_i      : in  std_logic_vector(BLK_AW-1 downto 0);
    read_data_o         : out std_logic_vector(31 downto 0);
    read_ack_o          : out std_logic;

    write_strobe_i      : in  std_logic;
    write_address_i     : in  std_logic_vector(BLK_AW-1 downto 0);
    write_data_i        : in  std_logic_vector(31 downto 0);
    write_ack_o         : out std_logic
);
end slow_ctrl;

architecture rtl of slow_ctrl is

signal read_addr        : natural range 0 to (2**read_address_i'length - 1);
signal write_addr       : natural range 0 to (2**write_address_i'length - 1);


begin

-- Unused outputs
read_ack_o <= '0';
write_ack_o <= '0';

read_addr <= to_integer(unsigned(read_address_i));
write_addr <= to_integer(unsigned(write_address_i));

--
-- Control System Interface
--
REG_WRITE : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
        else

            if (write_strobe_i = '1') then
                -- Input Select Control Registers

            end if;
        end if;
    end if;
end process;

--
-- Status Register Read
--
REG_READ : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            read_data_o <= (others => '0');
        else
            case (read_addr) is
                when SLOW_TEMP_PSU =>
                    read_data_o <= TEMP_PSU;
                when SLOW_TEMP_SFP =>
                    read_data_o <= TEMP_SFP;
                when SLOW_TEMP_ENC_L =>
                    read_data_o <= TEMP_ENC_L;
                when SLOW_TEMP_PICO =>
                    read_data_o <= TEMP_PICO;
                when SLOW_TEMP_ENC_R =>
                    read_data_o <= TEMP_ENC_R;
                when SLOW_ALIM_12V0 =>
                    read_data_o <= ALIM_12V0;
                when SLOW_PICO_5V0 =>
                    read_data_o <= PICO_5V0;
                when SLOW_IO_5V0 =>
                    read_data_o <= IO_5V0;
                when SLOW_SFP_3V3 =>
                    read_data_o <= SFP_3V3;
                when SLOW_FMC_15VN =>
                    read_data_o <= FMC_15VN;
                when SLOW_FMC_15VP =>
                    read_data_o <= FMC_15VP;
                when SLOW_ENC_24V =>
                    read_data_o <= ENC_24V;
                when SLOW_FMC_12V =>
                    read_data_o <= FMC_12V;
                when others =>
                    read_data_o <= (others => '0');
            end case;
        end if;
    end if;
end process;

--
-- Instantiate Delay Blocks for System and Position Bus Fields
--



end rtl;