--------------------------------------------------------------------------------
--  File:       ttlout_ctrl.vhd
--  Desc:       Autogenerated block control module.
--
--  Author:     Isa Uzun - Diamond Light Source
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.type_defines.all;
use work.addr_defines.all;
use work.top_defines.all;

entity ttlout_ctrl is
port (
    -- Clock and Reset
    clk_i               : in std_logic;
    reset_i             : in std_logic;
    sysbus_i            : in sysbus_t;
    posbus_i            : in posbus_t;
    -- Block Parameters
    val_o : out std_logic;
    -- Memory Bus Interface
    mem_cs_i            : in  std_logic;
    mem_wstb_i          : in  std_logic;
    mem_addr_i          : in  std_logic_vector(BLK_AW-1 downto 0);
    mem_dat_i           : in  std_logic_vector(31 downto 0);
    mem_dat_o           : out std_logic_vector(31 downto 0)
);
end ttlout_ctrl;

architecture rtl of ttlout_ctrl is

signal mem_addr : natural range 0 to (2**mem_addr_i'length - 1);

signal VAL      : std_logic_vector(31 downto 0);
signal VAL_WSTB : std_logic;
signal VAL_DLY      : std_logic_vector(31 downto 0);
signal VAL_DLY_WSTB : std_logic;

begin

mem_addr <= to_integer(unsigned(mem_addr_i));

--
-- Control System Interface
--
REG_WRITE : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            VAL <= (others => '0');
            VAL_WSTB <= '0';
            VAL_DLY <= (others => '0');
            VAL_DLY_WSTB <= '0';
        else
            VAL_WSTB <= '0';
            VAL_DLY_WSTB <= '0';

            if (mem_cs_i = '1' and mem_wstb_i = '1') then
                -- Input Select Control Registers
                if (mem_addr = TTLOUT_VAL) then
                    VAL <= mem_dat_i;
                    VAL_WSTB <= '1';
                end if;
                if (mem_addr = TTLOUT_VAL_DLY) then
                    VAL_DLY <= mem_dat_i;
                    VAL_DLY_WSTB <= '1';
                end if;

            end if;
        end if;
    end if;
end process;

--
-- Status Register Read
--
REG_READ : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            mem_dat_o <= (others => '0');
        else
            case (mem_addr) is
                when others =>
                    mem_dat_o <= (others => '0');
            end case;
        end if;
    end if;
end process;

--
-- Instantiate Delay Blocks for System and Position Bus Fields
--
bitmux_VAL : entity work.bitmux
port map (
    clk_i       => clk_i,
    sysbus_i    => sysbus_i,
    bit_o       => val_o,
    BITMUX_SEL  => VAL,
    BIT_DLY     => VAL_DLY
);




end rtl;