# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue.xci
# IP: The module: 'pulse_queue' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue/pulse_queue.xdc
# XDC: The top module name and the constraint reference have the same name: 'pulse_queue'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pulse_queue'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue.xci
# IP: The module: 'pulse_queue' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue/pulse_queue.xdc
# XDC: The top module name and the constraint reference have the same name: 'pulse_queue'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pulse_queue'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
