# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z030sbg485-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/managed_ip_project/managed_ip_project.cache/wt [current_project]
set_property parent.project_path /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/managed_ip_project/managed_ip_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_ip /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue.xci
set_property used_in_implementation false [get_files -all /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue.dcp]
set_property is_locked true [get_files /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top pulse_queue -part xc7z030sbg485-1 -mode out_of_context
rename_ref -prefix_all pulse_queue_
write_checkpoint -noxdef pulse_queue.dcp
catch { report_utilization -file pulse_queue_utilization_synth.rpt -pb pulse_queue_utilization_synth.pb }
if { [catch {
  file copy -force /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/managed_ip_project/managed_ip_project.runs/pulse_queue_synth_1/pulse_queue.dcp /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue.dcp
} _RESULT ] } { 
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue_funcsim.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/iu42/hardware/trunk/FPGA/PandA-Motion-Project/PandaFPGA/src/ip_repo/pulse_queue/pulse_queue_funcsim.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
