# AUTOGENERATED
# This is a script to add all of the tests and required hdl code for the
# testblock module to the vivado project

set_property SOURCE_SET sources_1 [get_filesets sim_1]

array set tests {
    testblock_1_tb 1
    testblock_2_tb 1
}

# add the module vhd code
add_files -norecurse $TOP_DIR/modules/testblock/hdl

# read xci files for any IP required by module

add_files -fileset sim_1 -norecurse \
    $BUILD_DIR/hdl_timing/testblock/timing001/hdl_timing.sv \
    $BUILD_DIR/hdl_timing/testblock/timing001/1testblockexpected.csv \
    $BUILD_DIR/hdl_timing/testblock/timing002/hdl_timing.sv \
    $BUILD_DIR/hdl_timing/testblock/timing002/2testblockexpected.csv \
    $TOP_DIR/modules/testblock/
