--------------------------------------------------------------------------------
--  File:       pulse_ctrl.vhd
--  Desc:       Autogenerated block control module.
--
--  Author:     Isa Uzun - Diamond Light Source
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.type_defines.all;
use work.addr_defines.all;
use work.top_defines.all;

entity pulse_ctrl is
port (
    -- Clock and Reset
    clk_i               : in std_logic;
    reset_i             : in std_logic;
    sysbus_i            : in sysbus_t;
    posbus_i            : in posbus_t;
    -- Block Parameters
    DELAY_L       : out std_logic_vector(31 downto 0);
    DELAY_L_WSTB  : out std_logic;
    DELAY_H       : out std_logic_vector(31 downto 0);
    DELAY_H_WSTB  : out std_logic;
    WIDTH_L       : out std_logic_vector(31 downto 0);
    WIDTH_L_WSTB  : out std_logic;
    WIDTH_H       : out std_logic_vector(31 downto 0);
    WIDTH_H_WSTB  : out std_logic;
    ERR_OVERFLOW       : in  std_logic_vector(31 downto 0);
    ERR_PERIOD       : in  std_logic_vector(31 downto 0);
    QUEUE       : in  std_logic_vector(31 downto 0);
    MISSED_CNT       : in  std_logic_vector(31 downto 0);
    inp_o : out std_logic;
    enable_o : out std_logic;
    -- Memory Bus Interface
    mem_cs_i            : in  std_logic;
    mem_wstb_i          : in  std_logic;
    mem_addr_i          : in  std_logic_vector(BLK_AW-1 downto 0);
    mem_dat_i           : in  std_logic_vector(31 downto 0);
    mem_dat_o           : out std_logic_vector(31 downto 0)
);
end pulse_ctrl;

architecture rtl of pulse_ctrl is

signal mem_addr : natural range 0 to (2**mem_addr_i'length - 1);

signal INP      : std_logic_vector(31 downto 0);
signal INP_WSTB : std_logic;
signal INP_DLY      : std_logic_vector(31 downto 0);
signal INP_DLY_WSTB : std_logic;
signal ENABLE      : std_logic_vector(31 downto 0);
signal ENABLE_WSTB : std_logic;
signal ENABLE_DLY      : std_logic_vector(31 downto 0);
signal ENABLE_DLY_WSTB : std_logic;

begin

mem_addr <= to_integer(unsigned(mem_addr_i));

--
-- Control System Interface
--
REG_WRITE : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            DELAY_L <= (others => '0');
            DELAY_L_WSTB <= '0';
            DELAY_H <= (others => '0');
            DELAY_H_WSTB <= '0';
            WIDTH_L <= (others => '0');
            WIDTH_L_WSTB <= '0';
            WIDTH_H <= (others => '0');
            WIDTH_H_WSTB <= '0';
            INP <= (others => '0');
            INP_WSTB <= '0';
            INP_DLY <= (others => '0');
            INP_DLY_WSTB <= '0';
            ENABLE <= (others => '0');
            ENABLE_WSTB <= '0';
            ENABLE_DLY <= (others => '0');
            ENABLE_DLY_WSTB <= '0';
        else
            DELAY_L_WSTB <= '0';
            DELAY_H_WSTB <= '0';
            WIDTH_L_WSTB <= '0';
            WIDTH_H_WSTB <= '0';
            INP_WSTB <= '0';
            INP_DLY_WSTB <= '0';
            ENABLE_WSTB <= '0';
            ENABLE_DLY_WSTB <= '0';

            if (mem_cs_i = '1' and mem_wstb_i = '1') then
                -- Input Select Control Registers
                if (mem_addr = PULSE_DELAY_L) then
                    DELAY_L <= mem_dat_i;
                    DELAY_L_WSTB <= '1';
                end if;
                if (mem_addr = PULSE_DELAY_H) then
                    DELAY_H <= mem_dat_i;
                    DELAY_H_WSTB <= '1';
                end if;
                if (mem_addr = PULSE_WIDTH_L) then
                    WIDTH_L <= mem_dat_i;
                    WIDTH_L_WSTB <= '1';
                end if;
                if (mem_addr = PULSE_WIDTH_H) then
                    WIDTH_H <= mem_dat_i;
                    WIDTH_H_WSTB <= '1';
                end if;
                if (mem_addr = PULSE_INP) then
                    INP <= mem_dat_i;
                    INP_WSTB <= '1';
                end if;
                if (mem_addr = PULSE_INP_DLY) then
                    INP_DLY <= mem_dat_i;
                    INP_DLY_WSTB <= '1';
                end if;
                if (mem_addr = PULSE_ENABLE) then
                    ENABLE <= mem_dat_i;
                    ENABLE_WSTB <= '1';
                end if;
                if (mem_addr = PULSE_ENABLE_DLY) then
                    ENABLE_DLY <= mem_dat_i;
                    ENABLE_DLY_WSTB <= '1';
                end if;

            end if;
        end if;
    end if;
end process;

--
-- Status Register Read
--
REG_READ : process(clk_i)
begin
    if rising_edge(clk_i) then
        if (reset_i = '1') then
            mem_dat_o <= (others => '0');
        else
            case (mem_addr) is
                when PULSE_ERR_OVERFLOW =>
                    mem_dat_o <= ERR_OVERFLOW;
                when PULSE_ERR_PERIOD =>
                    mem_dat_o <= ERR_PERIOD;
                when PULSE_QUEUE =>
                    mem_dat_o <= QUEUE;
                when PULSE_MISSED_CNT =>
                    mem_dat_o <= MISSED_CNT;
                when others =>
                    mem_dat_o <= (others => '0');
            end case;
        end if;
    end if;
end process;

--
-- Instantiate Delay Blocks for System and Position Bus Fields
--
bitmux_INP : entity work.bitmux
port map (
    clk_i       => clk_i,
    sysbus_i    => sysbus_i,
    bit_o       => inp_o,
    BITMUX_SEL  => INP,
    BIT_DLY     => INP_DLY
);

bitmux_ENABLE : entity work.bitmux
port map (
    clk_i       => clk_i,
    sysbus_i    => sysbus_i,
    bit_o       => enable_o,
    BITMUX_SEL  => ENABLE,
    BIT_DLY     => ENABLE_DLY
);




end rtl;