library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library work;
use work.support.all;
use work.top_defines.all;

entity <FB>_block is
generic (
    INST                : natural := 0
);
port (
    -- DO NOT EDIT BELOW THIS LINE ---------------------
    -- Standard FB Block ports, do not add to or delete
    clk_i               : in  std_logic;
    reset_i             : in  std_logic;
    -- System Bus Inputs
    bit_bus_i            : in  std_logic_vector(127 downto 0);
    pos_bus_i            : in  std32_array(31 downto 0);
    -- PandABlocks Memory Bus Interface
    read_strobe_i       : in  std_logic;
    read_address_i      : in  std_logic_vector(BLK_AW-1 downto 0);
    read_data_o         : out std_logic_vector(31 downto 0);
    read_ack_o          : out std_logic;

    write_strobe_i      : in  std_logic;
    write_address_i     : in  std_logic_vector(BLK_AW-1 downto 0);
    write_data_i        : in  std_logic_vector(31 downto 0);
    write_ack_o         : out std_logic;
    -- DO NOT EDIT ABOVE THIS LINE ---------------------

    -- FB Bit and Pos-type Outputs
    <bit_ports>_o       : out std_logic;
    <port_ports>_o      : out std_logic_vector(31 downto 0)
);
end <FB>_block;

architecture rtl of <FB>_block is

begin

--------------------------------------------------------------------------
-- Memory Control System Interface
-- INSTANTIATE AS AUTOGENERATED FROM CONFIG FILESET
--------------------------------------------------------------------------
<FB>_ctrl : entity work.<FB>_ctrl
port map (
    -- Clocks and Resets
    clk_i               => clk_i,
    reset_i             => reset_i,

    -- ADD CSR MAPPINGS HERE
    ...
    ...
    ...
);

--------------------------------------------------------------------------
-- Functional Block Core IP Instantiation
--------------------------------------------------------------------------
<FB>_inst : entity work.<FB>
port map (
    -- Clocks and Resets
    clk_i               => clk_i,
    reset_i             => reset_i,

    -- ADD CSR MAPPINGS HERE
    ...
    ...
    ...

    -- FB Bit and Pos-type Outputs
    <bit_ports>_o       => <bit_ports>_o,
    <port_ports>_o      => <pos_ports>_o

);

end rtl;

