name: "Perform Repetitive Tasks"
description: "Composite action that checks out repos, installs rclone, mounts S3 bucket, and gets container image"

inputs:
  username:
    required: true
  password:
    required: true

runs:
  using: "composite"
  steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: PandABlocks-fpga
          # require history to get back to last tag for version number of branches
          fetch-depth: 0
      - name: Checkout PandABlocks-rootfs
        uses: actions/checkout@v2
        with:
          repository: PandABlocks/PandABlocks-rootfs
          path: PandABlocks-rootfs
      # Installation of go & temporary rclone patch applied until symlinks issue using rclone mount is resolved (see below):
      # https://github.com/rclone/rclone/issues/2975
      - name: Install rclone patch
        shell: bash
        run: bash PandABlocks-fpga/.github/scripts/rclone-patch.sh

      # S3 bucket
      - name: Mount Vivado S3 bucket
        shell: bash
        run: sudo bash PandABlocks-fpga/.github/scripts/mount-s3-bucket.sh ${{ inputs.VIVADO_S3_ACCESS_KEY_ID }} ${{ inputs.VIVADO_S3_SECRET_ACCESS_KEY }}

      #Get container image
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: inputs.username
          password: inputs.password
