name: "Perform Repetitive Tasks"
description: "Composite action that checks out repos, installs rclone, mounts S3 bucket, and gets container image"

runs:
  using: "composite"
  steps:
      - name: Checkout PandABlocks-rootfs
        uses: actions/checkout@v4
        with:
          repository: PandABlocks/PandABlocks-rootfs
          path: repos/PandABlocks-rootfs
          fetch-depth: 0

      - name: Give runner build perms, and adjust repos config path
        shell: bash
        run: |
          sudo mkdir /build
          sudo chmod -R 777 /build