name: "Perform Repetitive Tasks"
description: "Composite action that checks out repos, installs rclone, mounts S3 bucket, and gets container image"

runs:
  using: "composite"
  steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: /repos/PandABlocks-fpga
          # require history to get back to last tag for version number of branches
          fetch-depth: 0
      - name: Checkout PandABlocks-rootfs
        uses: actions/checkout@v4
        with:
          repository: PandABlocks/PandABlocks-rootfs
          path: /repos/PandABlocks-rootfs
          fetch-depth: 0
