#!/bin/sh

# LED daemon definitions
LED_GPIO_BASE=334
STA_LED_OFFSET=25
DIA_LED_OFFSET=24

get_mac_address() {
    # Trying to address 0 sends a 0 byte which wakes up the EEPROM
    i2ctransfer -a -y 0 r1@0x0 &>/dev/null
    # Send command to read 32 bytes of OTP zone starting at offset 0
    # See script atsha240a-gen for more information, it was used to
    # generate the bytes in the request
    i2ctransfer -y 0 w8@0x64  0x3 0x7 0x2 0x81 0x0 0x0 0x0a 0x27
    # Reply structure: length(1b) + data(32b) + crc16(2b)
    resp=$(i2ctransfer -y 0 r35@0x64)
    # Extract the MAC address and format it
    resp=${resp:85:29}
    resp=${resp//0x/}
    echo ${resp// /:}
}
