# Ini file for the carrier blocks for PandABox. This replaces the panda_carrier
# module. The config files for each carrier block can be found in
# blocks/blockname
[.]

io: sfp: 0
    fmc: 1
options: 

[PCAP]
number: 1

[SYSTEM]
module: system_zynqmp
number: 1

[SI]
module: di
block: no_term_di
number: 2

[OC]
module: do
number: 2

[TTLIN]
module: di
number: 2

[TTLOUT]
module: fdly_do
number: 2

[TTLIO]
module: dio
number: 4

[ST_TTLIO]
module: st_dio
number: 4

[LVDSIO]
module: ext_dio
number: 2
