on:
  workflow_call:

jobs:
  make_boot:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: zynq
            app: PandABox-no-fmc
    runs-on:
      group: iris_runners
    container:
      image: docker.io/shihabdls/pandablocks-container-extension:v1.7
      options: --privileged
      volumes:
        - ${{github.workspace}}/repos:/repos
        - ${{github.workspace}}/build:/build

    steps:
      # Give runner perms
      - name: Give runner build perms
        id: give_perms
        run: |
          sudo mkdir /build
          sudo mkdir /repos
          sudo chmod -R 777 /build
          sudo chmod -R 777 /repos

      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Run action.yml
      - name: Checkout repos
        uses: ./.github/actions/setupenv

        # Generate bootable image
      - name: Make boot
        id: make_boot
        run: |
          cd /repos/PandABlocks-fpga && ln -s CONFIG.example CONFIG && make boot APP_NAME=${{ matrix.app }} && echo "done"
          exit

      # Artifacts
      - name: Upload boot
        uses: actions/upload-artifact@v2
        with:
          name: zpkgs
          path: ./build/boot*.zip
