on:
  workflow_call:

jobs:
  make_zpkg_aws:
    strategy:
      fail-fast: false
      matrix:
        app:
          ["xu5_st1-no-fmc","xu5_st1-fmc_acq430"]
    name: make zpkg on aws
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      # Git repositories
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Run Composite
        uses: ./.github/actions/setupenv
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      # Mount in rclone bucket from vm into conatiner
      - name: build carrier_ip and zpkg
        run: |
          sudo docker pull ghcr.io/pandablocks/pandablocks-dev-container:latest
          sudo docker run \
            -v "${{ github.workspace }}:/repos" \
            -v "${{ github.workspace }}/build:/build" \
            -v "/scratch/Xilinx:/scratch/Xilinx" \
            ghcr.io/pandablocks/pandablocks-dev-container:latest\
            /bin/bash -c \
            "cd PandABlocks-fpga && ln -s CONFIG.example CONFIG && make carrier_ip APP_NAME=${{ matrix.app }} && make zpkg APP_NAME=${{ matrix.app }}"

      # Artifacts
      - name: Upload zpkg
        uses: actions/upload-artifact@v2
        with:
          name: zpkgs
          path: ./build/panda-fpga@*.zpg
