on:
  workflow_call:

jobs:
  make_zpkg:
    strategy:
      fail-fast: false
      matrix:
        app: [
              "PandABox-no-fmc"
              ]
    runs-on:
      group: iris_runners
    container:
      image: docker.io/shihabdls/pandablocks-container-extension:v1.7
      options: --privileged

    steps:
      # Give runner perms
      - name: Give runner build perms
        id: give_perms
        run: |
          sudo mkdir /repos
          sudo mkdir /build
          sudo chmod -R 777 /build
          
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: repos/PandABlocks-fpga
          fetch-depth: 0

      - name: Checkout PandABlocks-rootfs
        uses: actions/checkout@v4
        with:
          repository: PandABlocks/PandABlocks-rootfs
          path: repos/PandABlocks-rootfs
          fetch-depth: 0

      - name: build carrier_ip and zpkg
        id: make_zpkg
        run: |
          cd repos/PandABlocks-fpga
          pwd
          ln -s CONFIG.example CONFIG && make carrier_ip APP_NAME=${{ matrix.app }} && make zpkg APP_NAME=${{ matrix.app }} && echo "done"
          exit

      # Artifacts
      - name: Upload zpkg
        uses: actions/upload-artifact@v2
        with:
          name: zpkgs
          path: ./build/panda-fpga@*.zpg