on:
  workflow_call:

jobs:
  make_zpkg:
    strategy:
      fail-fast: false
      matrix:
        app: [
              "PandABox-no-fmc"
              ]
    runs-on:
      group: iris_runners
    container:
      image: docker.io/shihabdls/pandablocks-container-extension:v1.7
      options: --privileged

    steps:
      # Give runner perms
      - name: Give runner build perms
        id: give_perms
        run: |
          sudo mkdir /build
          sudo mkdir /repos
          sudo chmod -R 777 /build
          cd /repos
          sudo mkdir /PandaBlocks-fpga
          cd /PandaBlocks-fpga
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run action.yml
      #- name: Checkout repos
      #  uses: ./.github/actions/setupenv

      - name: build carrier_ip and zpkg
        id: make_zpkg
        run: |
          ls
          cd PandABlocks-fpga && ln -s CONFIG.example CONFIG && make carrier_ip APP_NAME=${{ matrix.app }} && make zpkg APP_NAME=${{ matrix.app }} && echo "done"
          exit

      # Artifacts
      - name: Upload zpkg
        uses: actions/upload-artifact@v2
        with:
          name: zpkgs
          path: ./build/panda-fpga@*.zpg