on:
  workflow_call:
    secrets:
      VIVADO_S3_ACCESS_KEY_ID:
        required: true
      VIVADO_S3_SECRET_ACCESS_KEY:
        required: true

jobs:
  make_boot:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: zynq
            app: PandABox-no-fmc
          - platform: zynqmp
            app: xu5_st1-no-fmc
    runs-on:
      group: iris_runners
    container:
      image: shihabdls/pandablocks-container:latest
      volumes:
        - ${{github.workspace}}/repos:/repos
        - ${{github.workspace}}/build:/build
        - ${{github.workspace}}/scratch/Xilinx:/scratch/Xilinx

    steps:
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Run action.yml
      - name: Checkout and install rclone
        uses: ./.github/actions/setupenv

      - name: Print volumes and make config
        run: |
          mkdir -p /home/runner/.config/rclone
          cat >> /home/runner/.config/rclone/rclone.conf <<EOL
          [fpga-vivado]
          type = s3
          provider = Ceph
          env_auth = false
          access_key_id = ${{secrets.VIVADO_S3_ACCESS_KEY_ID}}
          secret_access_key = ${{secrets.VIVADO_S3_SECRET_ACCESS_KEY}}
          region =
          endpoint = https://s3.echo.stfc.ac.uk
          EOL
          ls -l /home/runner/.config/rclone
          
      # S3 bucket
      - name: Mount Vivado S3 bucket
        run: |
          rclone config file
          rclone mount --file-perms 0777 --attr-timeout=10m --no-modtime --read-only --daemon --allow-other --vfs-cache-mode full -l fpga-vivado:dls-controls-fpga-xilinx /scratch/Xilinx
          
      - name: Verify S3 Bucket Mounting
        run: |
          ls -l /scratch/Xilinx
        
      - name: boot step
        run: cd repos/PandABlocks-fpga && ln -s CONFIG.example CONFIG && make boot APP_NAME=${{ matrix.app }}

      # Artifacts
      - name: Upload boot
        uses: actions/upload-artifact@v2
        with:
          name: zpkgs
          path: ./build/boot*.zip
