on:
  workflow_call:

jobs:
  make_zpkg_aws:
    strategy:
      fail-fast: false
      matrix:
        app:
          ["xu5_st1-no-fmc","xu5_st1-fmc_acq430"]
    runs-on:
      group: iris_runners
    container:
        image: docker.io/shihabdls/pandablocks-container-extension:v2.5
        options: --privileged
    
    steps:
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: repos/PandABlocks-fpga
          fetch-depth: 0

      - name: Checkout rootfs, give perms, and adjust path
        uses: ./repos/PandABlocks-fpga/.github/actions/setupenv

      # Make large zpkgs
      - name: build carrier_ip and zpkg
        id: make_zpkg_aws
        run: |
          cd repos/PandABlocks-fpga && ln -s CONFIG.example CONFIG && make WORK_DIR=/__w/PandABlocks-FPGA/PandABlocks-FPGA carrier_ip APP_NAME=${{ matrix.app }} && make WORK_DIR=/__w/PandABlocks-FPGA/PandABlocks-FPGA zpkg APP_NAME=${{ matrix.app }}
          exit

      # Artifacts
      - name: Upload zpkg
        uses: actions/upload-artifact@v2
        with:
          name: zpkgs
          path: /build/panda-fpga@*.zpg