on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string
    secrets:
      VIVADO_S3_ACCESS_KEY_ID:
        required: true
      VIVADO_S3_SECRET_ACCESS_KEY:
        required: true

jobs:
  # Build rclone and mount S3 bucket
  setup_aws_runner:
    name: setup rclone and mount on runner
    runs-on: ${{ inputs.label }}
    steps:
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Run action.yml
      - name: Checkout and install rclone
        uses: ./.github/actions/setupenv

      # S3 bucket
      - name: Mount Vivado S3 bucket
        run: sudo bash PandABlocks-fpga/.github/scripts/mount-s3-bucket.sh ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }} ${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }}

      # Get container image
      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

