on:
  workflow_call:
   inputs:
    matrix:
     required: true
     type: string

jobs:
  testing_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "${{fromJson(inputs.matrix)}}"
