on:
  workflow_call:
    secrets:
      VIVADO_S3_ACCESS_KEY_ID:
        required: true
      VIVADO_S3_SECRET_ACCESS_KEY:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Run action.yml
      - name: Checkout and install rclone
        uses: ./.github/actions/setupenv

      # S3 bucket
      - name: Mount Vivado S3 bucket
        run: sudo bash PandABlocks-fpga/.github/scripts/mount-s3-bucket.sh ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }} ${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }}

      # Get container image
      - name: login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      # Run tests
      - name: Make python and hdl tests
        run: |
          docker pull ghcr.io/pandablocks/pandablocks-dev-container:latest
          docker run \
            -v "${{ github.workspace }}:/repos" \
            -v "${{ github.workspace }}/build:/build" \
            -v "/scratch/Xilinx:/scratch/Xilinx" \
            ghcr.io/pandablocks/pandablocks-dev-container:latest \
            /bin/bash -c \
            "cd PandABlocks-fpga && ln -s CONFIG.example CONFIG && make python_tests && make python_timing && \
            make autogen && make hdl_test"
