on:
  workflow_call:
    inputs:
      run_id:
        required: true
        type: string

jobs:
  test_backup:
    if: ${{ always() }}
    runs-on:
      group: iris_runners
    container:
        image: docker.io/shihabdls/pandablocks-container-extension:v2.5
        options: --privileged
    
    steps:
      - name: install gh cli
        run: curl -sS https://webi.sh/gh | sh
        
      - name: check for make error
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh auth login && gh run view ${{ inputs.run_id }} --log
    
