on:
  workflow_call:
    outputs:
      matrix:
        value: ${{jobs.test_matrix.outputs.matrix}}

jobs:
  test_matrx:
    steps:
      - name: Evaluate number of modules/tests & generate job matrix
        run: |
             bash repos/PandABlocks-fpga/.github/scripts/tests_group.sh "/__w/PandABlocks-FPGA/PandABlocks-FPGA/repos/PandABlocks-fpga/modules"
             json_content=$(cat github_tests.json)
             echo "$json_content" >> GITHUB_OUTPUT
