on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
        
jobs:
  test:
    strategy:
      fail-fast: false
      # Using generated matrix from previous job
      matrix: ${{fromJSON(inputs.matrix)}}
    runs-on:
      group: iris_runners
    container:
        image: docker.io/shihabdls/pandablocks-container-extension:v2.5
        options: --privileged

    steps:
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: repos/PandABlocks-fpga
          fetch-depth: 0

      - name: Checkout rootfs and give runner perms
        uses: ./repos/PandABlocks-fpga/.github/actions/setupenv

      # Run tests
      - name: Make python and hdl tests
        id: python_hdl_tests
        run: cd repos/PandABlocks-fpga && ln -s CONFIG.example CONFIG && make WORK_DIR=/__w/PandABlocks-FPGA/PandABlocks-FPGA hdl_test MODULES="${{matrix.modules}}" 