on:
  workflow_call:

jobs:
  test_matrx:
    runs-on:
      group: iris_runners
    container:
        image: docker.io/shihabdls/pandablocks-container-extension:v2.5
        options: --privileged
    outputs:
        matrix: ${{steps.make_matrix.outputs.matrix}}
    
    steps:
      - name: Evaluate number of modules/tests & generate job matrix
        id: make_matrix
        run: |
             bash repos/PandABlocks-fpga/.github/scripts/tests_group.sh "/__w/PandABlocks-FPGA/PandABlocks-FPGA/repos/PandABlocks-fpga/modules"
             json_content=$(cat github_tests.json)
             echo "$json_content" >> GITHUB_OUTPUT
  test:
    needs: test_matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.test_matrix.outputs.matrix)}}
    runs-on:
      group: iris_runners
    container:
        image: docker.io/shihabdls/pandablocks-container-extension:v2.5
        options: --privileged

    steps:
      # Necessary to find action.yml
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: repos/PandABlocks-fpga
          fetch-depth: 0

      - name: Checkout rootfs, give perms, and adjust path
        uses: ./repos/PandABlocks-fpga/.github/actions/setupenv

      # Run tests
      - name: Make python and hdl tests
        id: python_hdl_tests
        run: cd repos/PandABlocks-fpga && ln -s CONFIG.example CONFIG && make WORK_DIR=/__w/PandABlocks-FPGA/PandABlocks-FPGA hdl_test MODULES="${{matrix.modules}}"  
