on:
  workflow_call:
    inputs:
      run_id:
        required: true
        type: string

jobs:
  test_backup:
    strategy:
      fail-fast: true
      matrix:
        modules:
          [pcap, seq qdec pgen, pcomp lut div, pulse srgate div bits, counter filter posenc clock]
    runs-on:
      group: iris_runners
    container:
        image: docker.io/shihabdls/pandablocks-container-extension:v2.5
        options: --privileged
    
    steps:
      - name: install gh cli
        run: curl -sS https://webi.sh/gh | sh
        
      - name: check for make error
        run: gh run view ${{ inputs.run_id }} --log
    
