name: Code CI

on:
  # Only run on changes to branches with open PRs (UndoBranch)(N)
  pull_request:
    types: [opened, edited, synchronize]
  # Run after PR merged, on implicit push
  push:
    tags:
      - '*'
    branches: [master, actions_workflow_changes]

jobs:
  # Make Boot files
  make_boot:
    uses: ./.github/workflows/_make_boot.yml
    secrets:
      VIVADO_S3_ACCESS_KEY_ID: ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }}
      VIVADO_S3_SECRET_ACCESS_KEY: ${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }}

  # Make zpkg for FPGA apps
  make_zpkg:
    uses: ./.github/workflows/_make_zpkg.yml
    secrets:
      VIVADO_S3_ACCESS_KEY_ID: ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }}
      VIVADO_S3_SECRET_ACCESS_KEY: ${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }}

  test:
    uses: ./.github/workflows/_test.yml
    secrets:
      VIVADO_S3_ACCESS_KEY_ID: ${{ secrets.VIVADO_S3_ACCESS_KEY_ID }}
      VIVADO_S3_SECRET_ACCESS_KEY: ${{ secrets.VIVADO_S3_SECRET_ACCESS_KEY }}
  
  release:
      needs: [ make_boot, make_zpkg, test ]
      uses: ./.github/workflows/_release.yml

