name: Code CI

on:
  # Only run on changes to branches with open PRs
  pull_request:
    types: [opened, edited, synchronize]
  # Run after PR merged, on implicit push, and on tag pushes
  push:
    tags:
      - '*'
    branches: [master, iris_runners]

jobs:
  # Make Boot files
#  make_boot:
#    uses: ./.github/workflows/_make_boot.yml

  # Make zpkg for FPGA apps
#  make_zpkg:
#    uses: ./.github/workflows/_make_zpkg.yml

#  make_zpkg_aws:
#    uses: ./.github/workflows/_make_zpkg_aws.yml

  # Generate job matrix to evenly split tests
  test_matrix:
    uses: ./.github/workflows/_test_matrix.yml

  # Python and hdl tests
  test:
    needs: test_matrix
    uses: ./.github/workflows/_test.yml
    with:
      matrix: ${{needs.test_matrix.outputs.matrix}}

  test_backup:
    needs: [test_matrix, test]
    uses: ./.github/workflows/_test_backup.yml
    with:
      run_id: ${{needs.test.outputs.run_id}}

  # Optional revert on failed push workflow
#  undo:
#    needs: [ make_boot, make_zpkg, make_zpkg_aws, test ]
#    uses: ./.github/workflows/_undo.yml
  
  # Release on push to tag
#  release:
#    needs: [ make_boot, make_zpkg, make_zpkg_aws, test ]
#    uses: ./.github/workflows/_release.yml
